console.dir(document);
console.dir(document.body);
console.log(document.body);
let heading=document.getElementById("heading");
console.dir(heading);
console.dir(document.getElementsByClassName("heading1"));
console.log(document.getElementsByClassName("heading1"));
console.dir(document.querySelectorAll(".heading1"));
console.dir(document.querySelector("p"));
let element = document.querySelector("p");
console.log(element.tagName);
console.log(element.innerText);
console.log(element.innerHTML);
console.log(element.textContent);
let ele=document.querySelector("div");
console.log(ele);
console.log(ele.childNodes);
let s=document.querySelector("#div1");
console.log(s.innerText);
console.log(s.innerHTML);